//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientCurrencyConverter.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToInr", ReplyAction="http://tempuri.org/IService1/ConvertToInrResponse")]
        double ConvertToInr(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToInr", ReplyAction="http://tempuri.org/IService1/ConvertToInrResponse")]
        System.Threading.Tasks.Task<double> ConvertToInrAsync(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToNpr", ReplyAction="http://tempuri.org/IService1/ConvertToNprResponse")]
        double ConvertToNpr(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToNpr", ReplyAction="http://tempuri.org/IService1/ConvertToNprResponse")]
        System.Threading.Tasks.Task<double> ConvertToNprAsync(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToPkr", ReplyAction="http://tempuri.org/IService1/ConvertToPkrResponse")]
        double ConvertToPkr(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToPkr", ReplyAction="http://tempuri.org/IService1/ConvertToPkrResponse")]
        System.Threading.Tasks.Task<double> ConvertToPkrAsync(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToSl", ReplyAction="http://tempuri.org/IService1/ConvertToSlResponse")]
        double ConvertToSl(double gbp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConvertToSl", ReplyAction="http://tempuri.org/IService1/ConvertToSlResponse")]
        System.Threading.Tasks.Task<double> ConvertToSlAsync(double gbp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfClientCurrencyConverter.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfClientCurrencyConverter.ServiceReference1.IService1>, WcfClientCurrencyConverter.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConvertToInr(double gbp) {
            return base.Channel.ConvertToInr(gbp);
        }
        
        public System.Threading.Tasks.Task<double> ConvertToInrAsync(double gbp) {
            return base.Channel.ConvertToInrAsync(gbp);
        }
        
        public double ConvertToNpr(double gbp) {
            return base.Channel.ConvertToNpr(gbp);
        }
        
        public System.Threading.Tasks.Task<double> ConvertToNprAsync(double gbp) {
            return base.Channel.ConvertToNprAsync(gbp);
        }
        
        public double ConvertToPkr(double gbp) {
            return base.Channel.ConvertToPkr(gbp);
        }
        
        public System.Threading.Tasks.Task<double> ConvertToPkrAsync(double gbp) {
            return base.Channel.ConvertToPkrAsync(gbp);
        }
        
        public double ConvertToSl(double gbp) {
            return base.Channel.ConvertToSl(gbp);
        }
        
        public System.Threading.Tasks.Task<double> ConvertToSlAsync(double gbp) {
            return base.Channel.ConvertToSlAsync(gbp);
        }
    }
}
